apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-python-demo
spec:
  replicas: 1
  selector:
    matchLabels: { service: fastapi }
  template:
    metadata:
      labels: { service: fastapi }
    spec:
      containers:
      - name: fastapi-service
        image: svb96/python-application:latest   # <= YOUR IMAGE
        imagePullPolicy: Always                  # always fetch latest build :contentReference[oaicite:4]{index=4}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER   ; value: postgres
        - name: POSTGRES_DB     ; value: example
        - name: POSTGRES_SERVER ; value: postgres
        - name: POSTGRES_PORT   ; value: "5432"
        ports: [{ containerPort: 8001 }]
---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
spec:
  type: NodePort
  selector: { service: fastapi }
  ports:
  - port: 8001       # inside the cluster
    targetPort: 8001
    nodePort: 30001  # fixed host-side port
