name: ci

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 0) Bring the repo contents into the runner workspace
      - uses: actions/checkout@v4

      # 1) Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}     # e.g. svb96
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # your PAT

      # 2) Enable Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Build multi-arch image and push it
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/workflows/Dockerfile        # correct path to Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/python-application:latest
